-- 1. Check duplication step by step, starting with just first join
SELECT 
    'BASE_90D' as step,
    COUNT(*) as total_rows,
    COUNT(DISTINCT PATIENTID || CLM_DT) as distinct_combos
FROM (
    SELECT BASE.*, P90D.*
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE BASE
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D P90D
        ON P90D.PATIENTID = BASE.PATIENTID 
        AND P90D.CLM_DT = BASE.CLM_DT
)
UNION ALL
-- Add 180D
SELECT 
    'BASE_90D_180D' as step,
    COUNT(*) as total_rows,
    COUNT(DISTINCT PATIENTID || CLM_DT) as distinct_combos
FROM (
    SELECT BASE.*, P90D.*, P180D.*
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE BASE
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D P90D
        ON P90D.PATIENTID = BASE.PATIENTID 
        AND P90D.CLM_DT = BASE.CLM_DT
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_180D P180D
        ON P180D.PATIENTID = BASE.PATIENTID
        AND P180D.CLM_DT = BASE.CLM_DT
)
UNION ALL
-- Add GCN
SELECT 
    'BASE_90D_180D_GCN' as step,
    COUNT(*) as total_rows,
    COUNT(DISTINCT PATIENTID || CLM_DT) as distinct_combos
FROM (
    SELECT BASE.*, P90D.*, P180D.*, GCN.*
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE BASE
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D P90D
        ON P90D.PATIENTID = BASE.PATIENTID 
        AND P90D.CLM_DT = BASE.CLM_DT
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_180D P180D
        ON P180D.PATIENTID = BASE.PATIENTID
        AND P180D.CLM_DT = BASE.CLM_DT
    LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_GCN_HIST GCN
        ON GCN.PATIENTID = BASE.PATIENTID
        AND GCN.CLM_DT = BASE.CLM_DT
);
