-- Let's examine how 90D table is created
SELECT * 
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE 
WHERE PATIENTID IN (
    SELECT PATIENTID 
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D 
    GROUP BY PATIENTID, CLM_DT 
    HAVING COUNT(*) > 1
)
ORDER BY PATIENTID, CLM_DT;

-- Then check the JSON parsing logic:
SELECT 
    PATIENTID,
    CLM_DT,
    REQUEST_JSON,
    PARSE_JSON(REQUEST_JSON):demographic.latitude,
    PARSE_JSON(REQUEST_JSON):demographic.longitude
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE
WHERE PATIENTID IN (
    SELECT PATIENTID 
    FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D 
    GROUP BY PATIENTID, CLM_DT 
    HAVING COUNT(*) > 1
);
