-- Check if BASE table has these duplicates
SELECT PATIENTID, CLM_DT, COUNT(*) as dupe_count
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE
GROUP BY PATIENTID, CLM_DT
HAVING COUNT(*) > 1;

-- If BASE is clean, check 90D table formation
SELECT 
    BASE.PATIENTID, 
    BASE.CLM_DT,
    COUNT(*) as join_count,
    COUNT(DISTINCT P90D.some_key_column) as distinct_keys
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_BASE BASE
LEFT JOIN PL_APP_RPHAI.RAW_RPHAI.NBA5_PATIENT_90D P90D
    ON BASE.PATIENTID = P90D.PATIENTID
    AND BASE.CLM_DT = P90D.CLM_DT
GROUP BY BASE.PATIENTID, BASE.CLM_DT
HAVING COUNT(*) > 1;
